version: '3.8'
services:
  app:
    build:
      context: .
      target: production
    image: appointment:production
    volumes:
      - .:/app
    ports:
      - 3000:5000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      - db      
  
  
  db:
    image: postgres:15
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB =$DB_PRODUCTION
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - use_env_variable=$DATABASE_URL
volumes:
  pg-dev-data:

    