version: '3.8'
services:
  app:
    build:
      context: .
      target: production
    image: appointment:development
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DB_HOST=host.docker.internal
      - NODE_ENV=production
  
  db:
    image: postgres:15
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}

volumes:
  pg-dev-data:

    